---

- name: Install Libraries
  apt: 
    name: ['python-pip', 'python-dev']
    state: present

- pip:
    name: 
      - requests
      - pyyaml

- name: Create {{ home_path }}
  file: path={{ home_path }} state=directory owner=pi

- name: Copy monitor.py to raspberry pi
  copy: src=../monitor.py dest={{ home_path }}/monitor.py owner=pi mode="u+x"

- name: Copy publish.py to raspberry pi
  copy: src=../publisher.py dest={{ home_path }}/publisher.py owner=pi mode="u+x"

- name: Copy script configuration
  template:
    src: config.yml.j2
    dest: "{{ home_path }}/config.yml"

- name: Copy udev rules
  template:
    src: 90-co2mini.rules.j2
    dest: /etc/udev/rules.d/90-co2mini.rules

- name: Add user "pi" to "plugdev" group
  user:
    name: pi
    groups: plugdev
    append: yes

- name: Reload udev rules
  shell: udevadm trigger

- name: Register co2-monitor service
  template:
    src: co2-monitor.service.j2
    dest: /lib/systemd/system/co2-monitor.service

- name: Enable and restart co2-monitor service
  service: name=co2-monitor daemon_reload=yes state=restarted enabled=yes
